// src/components/Ready.tsx
import type { FC } from 'react';
import '../assets/global.css';
import Fade from 'react-reveal/Fade';

const Ready: FC = () => {
	const date = new Date();
	const minutes = date.getMinutes();

	return (
		<Fade bottom>
			<div className='mx-10 my-40 items-center grid bg-gray-900 p-10 rounded-3xl'>
				<div className='discord-messages'>
					<div className='discord-message'>
						<div className='discord-message-content'>
							<div className='discord-author-avatar'>
								<img src='/favicon.png' alt='' />
							</div>
							<div className='discord-message-body'>
								<div>
									<span className='discord-author-info'>
										<span className='discord-author-username'>Pyrite</span>
										<span className='discord-author-bot-tag'>Bot</span>
									</span>
									<span className='discord-message-timestamp'>
										Today at {date.getHours()}:{minutes < 10 ? '0' : ''}
										{minutes}
									</span>
								</div>
								<div className='discord-embed'>
									<div className='discord-embed-left-border' style={{ backgroundColor: '#2f3136' }}></div>
									<div className='discord-embed-container'>
										<div className='discord-embed-content'>
											<div>
												<div className='discord-embed-title'>
													<span>Ready to protect your server?</span>
												</div>
												<div className='discord-embed-description'>Start using Pyrite Bot now to get this features and more!</div>
											</div>
										</div>
									</div>
								</div>
								<div className='discord-buttons'>
									<a
										className='discord-button discord-button-link'
										href='https://discord.com/oauth2/authorize?client_id=1008400801628164096&amp;permissions=8&amp;scope=bot%20applications.commands'
										target='_blank'
										rel='noopener noreferrer'
									>
										Invite Me
										<span className='outbound-link-icon'>
											<svg
												xmlns='http://www.w3.org/2000/svg'
												aria-hidden='true'
												focusable='false'
												x='0px'
												y='0px'
												viewBox='0 0 100 100'
												width='15'
												height='15'
											>
												<path
													fill='currentColor'
													d='M18.8,85.1h56l0,0c2.2,0,4-1.8,4-4v-32h-8v28h-48v-48h28v-8h-32l0,0c-2.2,0-4,1.8-4,4v56C14.8,83.3,16.6,85.1,18.8,85.1z'
												></path>
												<polygon
													fill='currentColor'
													points='45.7,48.7 51.3,54.3 77.2,28.5 77.2,37.2 85.2,37.2 85.2,14.9 62.8,14.9 62.8,22.9 71.5,22.9'
												></polygon>
											</svg>
										</span>
									</a>
									<a
										className='discord-button discord-button-link'
										href='https://discord.com/oauth2/authorize?client_id=1008400801628164096&amp;permissions=8&amp;scope=bot%20applications.commands'
										target='_blank'
										rel='noopener noreferrer'
									>
										Support Server
										<span className='outbound-link-icon'>
											<svg
												xmlns='http://www.w3.org/2000/svg'
												aria-hidden='true'
												focusable='false'
												x='0px'
												y='0px'
												viewBox='0 0 100 100'
												width='15'
												height='15'
											>
												<path
													fill='currentColor'
													d='M18.8,85.1h56l0,0c2.2,0,4-1.8,4-4v-32h-8v28h-48v-48h28v-8h-32l0,0c-2.2,0-4,1.8-4,4v56C14.8,83.3,16.6,85.1,18.8,85.1z'
												></path>
												<polygon
													fill='currentColor'
													points='45.7,48.7 51.3,54.3 77.2,28.5 77.2,37.2 85.2,37.2 85.2,14.9 62.8,14.9 62.8,22.9 71.5,22.9'
												></polygon>
											</svg>
										</span>
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</Fade>
	);
};

export default Ready;

// src/components/Ready.svelte
<script>
	import { reveal } from 'svelte-reveal';
	import pyrite from '../assets/pyrite.webp';

	import '../assets/discord-messages.css';

	const date = new Date();
	const minutes = date.getMinutes();
	const time = `Today at ${date.getHours()}:${minutes < 10 ? '0' : ''}${minutes}`;
</script>

<div use:reveal="{{ y: 100, transition: 'fly' }}" class="mx-10 my-40 items-center grid bg-gray-900 p-3 rounded-[1.3em]">
	<div class="discord-messages">
		<div class="discord-message">
			<div class="discord-message-content">
				<div class="discord-author-avatar">
					<img src="{pyrite}" alt="" />
				</div>
				<div class="discord-message-body">
					<div>
						<span class="discord-author-info">
							<span class="discord-author-username">Pyrite</span>
							<span class="discord-author-bot-tag">Bot</span>
						</span>
						<span class="discord-message-timestamp">
							{time}
						</span>
					</div>
					<div class="discord-embed">
						<div class="discord-embed-left-border" style="{{ backgroundColor: '#2f3136' }}"></div>
						<div class="discord-embed-container">
							<div class="discord-embed-content">
								<div>
									<div class="discord-embed-title">
										<span>Ready to protect your server?</span>
									</div>
									<div class="discord-embed-description">Start using Pyrite Bot now to get this features and more!</div>
								</div>
							</div>
						</div>
					</div>
					<div class="discord-buttons">
						<a
							class="discord-button discord-button-link"
							href="https://discord.com/oauth2/authorize?client_id=1008400801628164096&amp;permissions=8&amp;scope=bot%20applications.commands"
							target="_blank"
							rel="noopener noreferrer"
						>
							Invite Me
							<span class="outbound-link-icon">
								<svg
									xmlns="http://www.w3.org/2000/svg"
									aria-hidden="true"
									focusable="false"
									x="0px"
									y="0px"
									viewBox="0 0 100 100"
									width="15"
									height="15"
								>
									<path
										fill="currentColor"
										d="M18.8,85.1h56l0,0c2.2,0,4-1.8,4-4v-32h-8v28h-48v-48h28v-8h-32l0,0c-2.2,0-4,1.8-4,4v56C14.8,83.3,16.6,85.1,18.8,85.1z"></path>
									<polygon fill="currentColor" points="45.7,48.7 51.3,54.3 77.2,28.5 77.2,37.2 85.2,37.2 85.2,14.9 62.8,14.9 62.8,22.9 71.5,22.9"
									></polygon>
								</svg>
							</span>
						</a>
						<a
							class="discord-button discord-button-link"
							href="https://discord.com/oauth2/authorize?client_id=1008400801628164096&amp;permissions=8&amp;scope=bot%20applications.commands"
							target="_blank"
							rel="noopener noreferrer"
						>
							Support Server
							<span class="outbound-link-icon">
								<svg
									xmlns="http://www.w3.org/2000/svg"
									aria-hidden="true"
									focusable="false"
									x="0px"
									y="0px"
									viewBox="0 0 100 100"
									width="15"
									height="15"
								>
									<path
										fill="currentColor"
										d="M18.8,85.1h56l0,0c2.2,0,4-1.8,4-4v-32h-8v28h-48v-48h28v-8h-32l0,0c-2.2,0-4,1.8-4,4v56C14.8,83.3,16.6,85.1,18.8,85.1z"></path>
									<polygon fill="currentColor" points="45.7,48.7 51.3,54.3 77.2,28.5 77.2,37.2 85.2,37.2 85.2,14.9 62.8,14.9 62.8,22.9 71.5,22.9"
									></polygon>
								</svg>
							</span>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
